S3_BUCKET_NAME: "wrany-assets"
AWS_ACCESS_KEY_ID: "AKIAIBGZXMYWI5QZHSHQ"
AWS_SECRET_ACCESS_KEY: "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"

#env.rb
#ENV['S3_BUCKET_NAME'] = 'wrany-assets'
#ENV['AWS_ACCESS_KEY_ID'] = 'AKIAIBGZXMYWI5QZHSHQ'
#ENV['AWS_SECRET_ACCESS_KEY'] = '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'

# config/initializers/paperclip.rb
#Paperclip::Attachment.default_options[:url] = 'wrany.s3.amazonaws.com'
#Paperclip::Attachment.default_options[:path] = '/:class/:attachment/:id_partition/:style/:filename'